//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanguagePack {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LanguagePack.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 接受 的本地化字符串。
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应收账款 的本地化字符串。
        /// </summary>
        public static string AccountReceivable {
            get {
                return ResourceManager.GetString("AccountReceivable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应收日期 的本地化字符串。
        /// </summary>
        public static string AccountReceivableDate {
            get {
                return ResourceManager.GetString("AccountReceivableDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 动作 的本地化字符串。
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 动作显示名称 的本地化字符串。
        /// </summary>
        public static string ActionDisplayName {
            get {
                return ResourceManager.GetString("ActionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 动作名称 的本地化字符串。
        /// </summary>
        public static string ActionName {
            get {
                return ResourceManager.GetString("ActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 活动内容 的本地化字符串。
        /// </summary>
        public static string ActivityContent {
            get {
                return ResourceManager.GetString("ActivityContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报名截止日期 的本地化字符串。
        /// </summary>
        public static string ActivityDeadline {
            get {
                return ResourceManager.GetString("ActivityDeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 活动地点 的本地化字符串。
        /// </summary>
        public static string ActivitySite {
            get {
                return ResourceManager.GetString("ActivitySite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 活动开始时间 的本地化字符串。
        /// </summary>
        public static string ActivityStartDateTime {
            get {
                return ResourceManager.GetString("ActivityStartDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 活动主题 的本地化字符串。
        /// </summary>
        public static string ActivityTitle {
            get {
                return ResourceManager.GetString("ActivityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地址 的本地化字符串。
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部 的本地化字符串。
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 金额 的本地化字符串。
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 区域 的本地化字符串。
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 区域显示名称 的本地化字符串。
        /// </summary>
        public static string AreaDisplayName {
            get {
                return ResourceManager.GetString("AreaDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 区域名称 的本地化字符串。
        /// </summary>
        public static string AreaName {
            get {
                return ResourceManager.GetString("AreaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 附件 的本地化字符串。
        /// </summary>
        public static string Attachment {
            get {
                return ResourceManager.GetString("Attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返回 的本地化字符串。
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始时间 的本地化字符串。
        /// </summary>
        public static string BeginTime {
            get {
                return ResourceManager.GetString("BeginTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 业务 的本地化字符串。
        /// </summary>
        public static string Business {
            get {
                return ResourceManager.GetString("Business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 业务机会 的本地化字符串。
        /// </summary>
        public static string BusinessChance {
            get {
                return ResourceManager.GetString("BusinessChance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 业务机会 的本地化字符串。
        /// </summary>
        public static string BusinessChanceName {
            get {
                return ResourceManager.GetString("BusinessChanceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 业务名称 的本地化字符串。
        /// </summary>
        public static string BusinessName {
            get {
                return ResourceManager.GetString("BusinessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 业务状态 的本地化字符串。
        /// </summary>
        public static string BusinessState {
            get {
                return ResourceManager.GetString("BusinessState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 业务状态 的本地化字符串。
        /// </summary>
        public static string BusinessStateName {
            get {
                return ResourceManager.GetString("BusinessStateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日历 的本地化字符串。
        /// </summary>
        public static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 颜色 的本地化字符串。
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 沟通结果 的本地化字符串。
        /// </summary>
        public static string CommunicateResult {
            get {
                return ResourceManager.GetString("CommunicateResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 沟通内容 的本地化字符串。
        /// </summary>
        public static string CommunicationContent {
            get {
                return ResourceManager.GetString("CommunicationContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公司 的本地化字符串。
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认密码 的本地化字符串。
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联系人 的本地化字符串。
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联系人名称 的本地化字符串。
        /// </summary>
        public static string ContactName {
            get {
                return ResourceManager.GetString("ContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内容 的本地化字符串。
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控制器显示名称 的本地化字符串。
        /// </summary>
        public static string ControllerDisplayName {
            get {
                return ResourceManager.GetString("ControllerDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控制器名称 的本地化字符串。
        /// </summary>
        public static string ControllerName {
            get {
                return ResourceManager.GetString("ControllerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数量 的本地化字符串。
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建 的本地化字符串。
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建日期 的本地化字符串。
        /// </summary>
        public static string CreatedDate {
            get {
                return ResourceManager.GetString("CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建知识 的本地化字符串。
        /// </summary>
        public static string CreateKnowledge {
            get {
                return ResourceManager.GetString("CreateKnowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建计划 的本地化字符串。
        /// </summary>
        public static string CreatePlan {
            get {
                return ResourceManager.GetString("CreatePlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建项目 的本地化字符串。
        /// </summary>
        public static string CreateProject {
            get {
                return ResourceManager.GetString("CreateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户 的本地化字符串。
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户等级 的本地化字符串。
        /// </summary>
        public static string CustomerLevel {
            get {
                return ResourceManager.GetString("CustomerLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户等级 的本地化字符串。
        /// </summary>
        public static string CustomerLevelName {
            get {
                return ResourceManager.GetString("CustomerLevelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户名称 的本地化字符串。
        /// </summary>
        public static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户类型 的本地化字符串。
        /// </summary>
        public static string CustomerType {
            get {
                return ResourceManager.GetString("CustomerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户类型 的本地化字符串。
        /// </summary>
        public static string CustomerTypeName {
            get {
                return ResourceManager.GetString("CustomerTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日 的本地化字符串。
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部门 的本地化字符串。
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部门编码 的本地化字符串。
        /// </summary>
        public static string DepartmentCode {
            get {
                return ResourceManager.GetString("DepartmentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部门名称 的本地化字符串。
        /// </summary>
        public static string DepartmentName {
            get {
                return ResourceManager.GetString("DepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 桌面 的本地化字符串。
        /// </summary>
        public static string Desktop {
            get {
                return ResourceManager.GetString("Desktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看 的本地化字符串。
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 差额 的本地化字符串。
        /// </summary>
        public static string Difference {
            get {
                return ResourceManager.GetString("Difference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁用 的本地化字符串。
        /// </summary>
        public static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示 的本地化字符串。
        /// </summary>
        public static string Display {
            get {
                return ResourceManager.GetString("Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示名称 的本地化字符串。
        /// </summary>
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮箱 的本地化字符串。
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表情 的本地化字符串。
        /// </summary>
        public static string Emoticon {
            get {
                return ResourceManager.GetString("Emoticon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用 的本地化字符串。
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束日期 的本地化字符串。
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束时间 的本地化字符串。
        /// </summary>
        public static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 企业 的本地化字符串。
        /// </summary>
        public static string Enterprise {
            get {
                return ResourceManager.GetString("Enterprise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 企业名称 的本地化字符串。
        /// </summary>
        public static string EnterpriseName {
            get {
                return ResourceManager.GetString("EnterpriseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 企业简称 的本地化字符串。
        /// </summary>
        public static string EnterpriseShortName {
            get {
                return ResourceManager.GetString("EnterpriseShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出 的本地化字符串。
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 扩展 的本地化字符串。
        /// </summary>
        public static string Extension {
            get {
                return ResourceManager.GetString("Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 否 的本地化字符串。
        /// </summary>
        public static string False {
            get {
                return ResourceManager.GetString("False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传真 的本地化字符串。
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件地址 的本地化字符串。
        /// </summary>
        public static string FileUrl {
            get {
                return ResourceManager.GetString("FileUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成 的本地化字符串。
        /// </summary>
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成时间 的本地化字符串。
        /// </summary>
        public static string FinishTime {
            get {
                return ResourceManager.GetString("FinishTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流程 的本地化字符串。
        /// </summary>
        public static string Flow {
            get {
                return ResourceManager.GetString("Flow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流程名称 的本地化字符串。
        /// </summary>
        public static string FlowName {
            get {
                return ResourceManager.GetString("FlowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流程任务 的本地化字符串。
        /// </summary>
        public static string FlowTask {
            get {
                return ResourceManager.GetString("FlowTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全局 的本地化字符串。
        /// </summary>
        public static string Global {
            get {
                return ResourceManager.GetString("Global", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Google事件编号 的本地化字符串。
        /// </summary>
        public static string GoogleEventEntryId {
            get {
                return ResourceManager.GetString("GoogleEventEntryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Google账户密码 的本地化字符串。
        /// </summary>
        public static string GooglePassword {
            get {
                return ResourceManager.GetString("GooglePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Google账户 的本地化字符串。
        /// </summary>
        public static string GoogleUserName {
            get {
                return ResourceManager.GetString("GoogleUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 头像 的本地化字符串。
        /// </summary>
        public static string Head {
            get {
                return ResourceManager.GetString("Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帮助 的本地化字符串。
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主机 的本地化字符串。
        /// </summary>
        public static string Host {
            get {
                return ResourceManager.GetString("Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图标 的本地化字符串。
        /// </summary>
        public static string Ico {
            get {
                return ResourceManager.GetString("Ico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编号 的本地化字符串。
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图 的本地化字符串。
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入 的本地化字符串。
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已开发票 的本地化字符串。
        /// </summary>
        public static string Invoice {
            get {
                return ResourceManager.GetString("Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发票类型 的本地化字符串。
        /// </summary>
        public static string InvoiceType {
            get {
                return ResourceManager.GetString("InvoiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IP 的本地化字符串。
        /// </summary>
        public static string IP {
            get {
                return ResourceManager.GetString("IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关键词 的本地化字符串。
        /// </summary>
        public static string Keyword {
            get {
                return ResourceManager.GetString("Keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 知识内容 的本地化字符串。
        /// </summary>
        public static string KnowledgeContent {
            get {
                return ResourceManager.GetString("KnowledgeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 知识标题 的本地化字符串。
        /// </summary>
        public static string KnowledgeTitle {
            get {
                return ResourceManager.GetString("KnowledgeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上级项目信息 的本地化字符串。
        /// </summary>
        public static string LastProjectInfo {
            get {
                return ResourceManager.GetString("LastProjectInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 负责人 的本地化字符串。
        /// </summary>
        public static string Leader {
            get {
                return ResourceManager.GetString("Leader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最大用户 的本地化字符串。
        /// </summary>
        public static string MaxUser {
            get {
                return ResourceManager.GetString("MaxUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 消息 的本地化字符串。
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 里程碑 的本地化字符串。
        /// </summary>
        public static string Milestone {
            get {
                return ResourceManager.GetString("Milestone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移动电话 的本地化字符串。
        /// </summary>
        public static string MobilePhone {
            get {
                return ResourceManager.GetString("MobilePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模块 的本地化字符串。
        /// </summary>
        public static string Module {
            get {
                return ResourceManager.GetString("Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 月 的本地化字符串。
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新密码 的本地化字符串。
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 旧密码 的本地化字符串。
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实收账款 的本地化字符串。
        /// </summary>
        public static string PaidIn {
            get {
                return ResourceManager.GetString("PaidIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实收日期 的本地化字符串。
        /// </summary>
        public static string PaidInDate {
            get {
                return ResourceManager.GetString("PaidInDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数 的本地化字符串。
        /// </summary>
        public static string Parameter {
            get {
                return ResourceManager.GetString("Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 周期 的本地化字符串。
        /// </summary>
        public static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片 的本地化字符串。
        /// </summary>
        public static string Picture {
            get {
                return ResourceManager.GetString("Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计划 的本地化字符串。
        /// </summary>
        public static string Plan {
            get {
                return ResourceManager.GetString("Plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计划主题 的本地化字符串。
        /// </summary>
        public static string PlanTitle {
            get {
                return ResourceManager.GetString("PlanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计划类型 的本地化字符串。
        /// </summary>
        public static string PlanType {
            get {
                return ResourceManager.GetString("PlanType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 人数 的本地化字符串。
        /// </summary>
        public static string Population {
            get {
                return ResourceManager.GetString("Population", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 职务 的本地化字符串。
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮编 的本地化字符串。
        /// </summary>
        public static string Postcode {
            get {
                return ResourceManager.GetString("Postcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目信息 的本地化字符串。
        /// </summary>
        public static string ProjectInfo {
            get {
                return ResourceManager.GetString("ProjectInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目信息 的本地化字符串。
        /// </summary>
        public static string ProjectInfoId {
            get {
                return ResourceManager.GetString("ProjectInfoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目状态 的本地化字符串。
        /// </summary>
        public static string ProjectInfoState {
            get {
                return ResourceManager.GetString("ProjectInfoState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目状态 的本地化字符串。
        /// </summary>
        public static string ProjectInfoStateName {
            get {
                return ResourceManager.GetString("ProjectInfoStateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目名称 的本地化字符串。
        /// </summary>
        public static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目目标 的本地化字符串。
        /// </summary>
        public static string ProjectObjective {
            get {
                return ResourceManager.GetString("ProjectObjective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目标签 的本地化字符串。
        /// </summary>
        public static string ProjectTag {
            get {
                return ResourceManager.GetString("ProjectTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目任务 的本地化字符串。
        /// </summary>
        public static string ProjectTask {
            get {
                return ResourceManager.GetString("ProjectTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目任务名称 的本地化字符串。
        /// </summary>
        public static string ProjectTaskName {
            get {
                return ResourceManager.GetString("ProjectTaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目任务说明 的本地化字符串。
        /// </summary>
        public static string ProjectTaskObjective {
            get {
                return ResourceManager.GetString("ProjectTaskObjective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目成员 的本地化字符串。
        /// </summary>
        public static string ProjectUsers {
            get {
                return ResourceManager.GetString("ProjectUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公开 的本地化字符串。
        /// </summary>
        public static string Public {
            get {
                return ResourceManager.GetString("Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等级 的本地化字符串。
        /// </summary>
        public static string Raty {
            get {
                return ResourceManager.GetString("Raty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记录编号 的本地化字符串。
        /// </summary>
        public static string RecordId {
            get {
                return ResourceManager.GetString("RecordId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新 的本地化字符串。
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册 的本地化字符串。
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注 的本地化字符串。
        /// </summary>
        public static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记住 的本地化字符串。
        /// </summary>
        public static string Remember {
            get {
                return ResourceManager.GetString("Remember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提醒时间 的本地化字符串。
        /// </summary>
        public static string RemindTime {
            get {
                return ResourceManager.GetString("RemindTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重复新密码 的本地化字符串。
        /// </summary>
        public static string ReNewPassword {
            get {
                return ResourceManager.GetString("ReNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回复 的本地化字符串。
        /// </summary>
        public static string Reply {
            get {
                return ResourceManager.GetString("Reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色 的本地化字符串。
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色名 的本地化字符串。
        /// </summary>
        public static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索 的本地化字符串。
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排序 的本地化字符串。
        /// </summary>
        public static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始日期 的本地化字符串。
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始时间 的本地化字符串。
        /// </summary>
        public static string StarTime {
            get {
                return ResourceManager.GetString("StarTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始搜索 的本地化字符串。
        /// </summary>
        public static string StartSearch {
            get {
                return ResourceManager.GetString("StartSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始时间 的本地化字符串。
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 统计 的本地化字符串。
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统区域 的本地化字符串。
        /// </summary>
        public static string SysArea {
            get {
                return ResourceManager.GetString("SysArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统编号 的本地化字符串。
        /// </summary>
        public static string SystemId {
            get {
                return ResourceManager.GetString("SystemId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标签 的本地化字符串。
        /// </summary>
        public static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新窗口 的本地化字符串。
        /// </summary>
        public static string TargetBlank {
            get {
                return ResourceManager.GetString("TargetBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电话 的本地化字符串。
        /// </summary>
        public static string Telephony {
            get {
                return ResourceManager.GetString("Telephony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主题 的本地化字符串。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 今天 的本地化字符串。
        /// </summary>
        public static string ToDay {
            get {
                return ResourceManager.GetString("ToDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是 的本地化字符串。
        /// </summary>
        public static string True {
            get {
                return ResourceManager.GetString("True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新日期 的本地化字符串。
        /// </summary>
        public static string UpdatedDate {
            get {
                return ResourceManager.GetString("UpdatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网址 的本地化字符串。
        /// </summary>
        public static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户 的本地化字符串。
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户中心 的本地化字符串。
        /// </summary>
        public static string UserCenter {
            get {
                return ResourceManager.GetString("UserCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名被禁用 的本地化字符串。
        /// </summary>
        public static string UserDisabled {
            get {
                return ResourceManager.GetString("UserDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名 的本地化字符串。
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名密码错误 的本地化字符串。
        /// </summary>
        public static string UserNamePasswordError {
            get {
                return ResourceManager.GetString("UserNamePasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有效期 的本地化字符串。
        /// </summary>
        public static string Validity {
            get {
                return ResourceManager.GetString("Validity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 周 的本地化字符串。
        /// </summary>
        public static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工作流名称 的本地化字符串。
        /// </summary>
        public static string WorkFlowName {
            get {
                return ResourceManager.GetString("WorkFlowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工作流步骤名称 的本地化字符串。
        /// </summary>
        public static string WorkFlowStepName {
            get {
                return ResourceManager.GetString("WorkFlowStepName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 年 的本地化字符串。
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
